#!/usr/bin/env bash

docker run --name mysql --net="host" -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=poeatlas -e MYSQL_ROOT_HOST=127.0.0.1 -d mysql/mysql-server

while docker ps | grep mysql | grep -qv healthy; do
    docker ps
    sleep 1
done

# docker run --rm --name cli --link mysql:mysql -e JAVA_OPTS="-Dspring.datasource.url=jdbc:mysql://mysql:3306/poeatlas?useSSL=false" poeatlas/cli dat
docker run --rm --name cli --net="host" poeatlas/cli dat
docker stop mysql
docker rm -fv mysql