#!/bin/bash -e

MIPMAP=1

cleanup() {
    docker stop mysql
    docker rm -fv mysql
}

trap "cleanup" INT TERM EXIT

docker run --name mysql \
    -e MYSQL_DATABASE=poeatlas \
    -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
    -e MYSQL_USER=poeatlas \
    -e MYSQL_PASSWORD=poeatlas\
    -d mysql/mysql-server

while docker ps | grep mysql | grep -qv healthy; do
    # after 10 minutes, fails
    sleep 1
done

JAVA_OPTS="-Dspring.datasource.url=\"jdbc:mysql://mysql:3306/poeatlas?useSSL=false\""
JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.username=\"poeatlas\""
JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.password=\"poeatlas\""

docker run --rm --name cli --link mysql:mysql \
    -e JAVA_OPTS="$JAVA_OPTS" \
    -v $PWD:/usr/src/app \
    poeatlas/cli \
    dat -input /usr/src/app/Data/ -output /usr/src/app/output/atlas.json

FOO=$(find . -name '*.dds')

docker run --rm --name cli --link mysql:mysql \
    -e JAVA_OPTS="$JAVA_OPTS" \
    -v $PWD:/usr/src/app \
    -P \
    poeatlas/cli \
    dds -mipmap ${MIPMAP} -root /usr/src/app ${FOO}

cp -Rf ./output/atlas.json ./atlas-ui/src/resources/atlas.json
cd atlas-ui
npm run build


#    -it \
# bash

#docker run --rm --name cli --net="host" poeatlas/cli dat